clone:
  default:
    image: plugins/git
    depth: 50
    recursive: false
    
pipeline:
  resolve:
    image: debian
    commands:
      - echo "nameserver 10.100.0.10" > /etc/resolv.conf
      - cat /etc/resolv.conf
      - echo "BBBBB"
      - cat /etc/hosts
      - ping -c 3 140.82.118.4
    when:
      status: [ success, failure ]
