clone:
  default:
    image: plugins/git
    depth: 50
    recursive: false
    
pipeline:
  resolve:
    image: ubuntu
    commands:
      - cat /etc/resolv.conf
      - echo "BBBBB"
      - cat /etc/hosts
      - ping github.com
    when:
      status: [ success, failure ]
