clone:
  default:
    image: plugins/git
    depth: 50
    recursive: false
    
pipeline:
  resolve:
    image: alpine
    commands:
      - cat /etc/resolv.conf
      - echo "BBBBB"
      - ping -c 3 ukr.net
    when:
      status: [ success, failure ]
